[main]

apikey = "1234567890"
apiserver = "api.dockerstack.in"
log = "/var/log/agent.log"
interface ="eth1"

[storage]
gdrive=""
gusername=""
gpassword=""

[plugins]
apios=true

[security]
https=false

